Refactor child components to functional ones
ChaabaneAnas/Math-Magicians pull request #4
Opened 2022-09-09 17:25 UTC by ChaabaneAnas

## CHANGES
- refactor `keyboard` component to a functional one
- refactor `display` component to a functional one
refactor `operations` component to a functional one

2022-09-09 18:02 UTC, codepantha requested changes
# STATUS: REQUIRES CHANGES ♻️ 

## Hi @ChaabaneAnas 👋, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights 🎯 
✔️ Descriptive PR
✔️ Used correct GitFlow
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-09 18:02 UTC, codepantha commented on src/Components/calculator.js
> +
- [ ] Please don't disable the linters. They are there to help you adhere to style guidelines and write better code 😎

2022-09-09 22:18 UTC, ChaabaneAnas commented on src/Components/calculator.js
> +
@codepantha I do understand that they exist for a good reason ...
but some of them are not being fixed ...

2022-09-09 23:51 UTC, mateo951 approved these changes
### Hi @ChaabaneAnas, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🐐 
### Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-10 00:14 UTC, ChaabaneAnas commented
thank you so much

2022-09-10 00:14 UTC, merged